service: microservice-reference

custom:
  environment: ${opt:stage, 'development'}
  bucketName: "${self:custom.environment}-thisbucket"
  region: ${opt:region, 'eu-west-2'}

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-admin
  region: "${self:custom.region}"
  endpointType: REGIONAL
  stage: ${opt:stage, 'development'}
  timeout: 15
  memorySize: 128
  role: arn:aws:iam::#{AWS::AccountId}:role/WOZiTech_eu_west_2_tfl_lambda_role

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - '**/*'
    - .git/**

functions:
  hello:
    handler: hello.handler
    events:
      - http:
          path: hello
          method: get
    tags:
      endpoint: "hello"
      module: "hello"
    package:
      include:
        - hello.js

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-include-dependencies